steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/food-delivery-trainer:latest', '.']
    id: 'Build Trainer'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/food-delivery-predictor:latest', './prediction_server']
    id: 'Build Predictor'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/food-delivery-trainer:latest']
    id: 'Push Trainer'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/food-delivery-predictor:latest']
    id: 'Push Predictor'
images:
  - 'gcr.io/${PROJECT_ID}/food-delivery-trainer:latest'
  - 'gcr.io/${PROJECT_ID}/food-delivery-predictor:latest'
options:
  logging: CLOUD_LOGGING_ONLY