steps:
  # 1. Build the training container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/food-delivery-trainer:latest', '.']
    id: 'Build Image'

  # 2. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/food-delivery-trainer:latest']
    id: 'Push Image'

# Store the image in Container Registry
images:
  - 'gcr.io/${PROJECT_ID}/food-delivery-trainer:latest'

# Add logging options to resolve the service account issue
options:
  logging: CLOUD_LOGGING_ONLY